#define DATA_IMPLEMENTATION // for data.c --> global variables will be defined in this translation unit
#include "rayverse.h"

#include "intrinsics.c"
#include "mathutil.c"
#include "sysutils.c"

#ifdef _WIN32
// Source files specific to Windows
#include "win32_opengl.c"
#include "win32_sound.c"
#include "win32_main.c"
#else
// Source files specific to Linux / macOS
#include "linux_opengl.c"
#include "linux_sound.c"
#include "linux_main.c"
#endif

// Misc source files, need cleanup
#include "engine.c"
#include "render.c"
#include "misc_source.c"

// Source files in (mostly) alphabetical order, corresponding to a possible ordering of the PC version's sources
#include "lowlevel.c"
#include "pcmain.c"
#include "action.c"
#include "affiche.c"
#include "araignee.c"
#include "audiocd.c"
#include "basic.c"
#include "bat.c"
#include "bbmont.c"
#include "blacktoon.c"
#include "blood.c"
#include "bonus.c"
#include "box.c"
#include "blocs.c"
#include "breakout.c"
#include "cage.c"
#include "clown.c"
#include "collision.c"
#include "compress.c"
#include "cymbal.c"
#include "dark.c"
#include "display.c"
#include "cheat.c"
#include "effect.c"
#include "fee.c"
#include "frame.c"
#include "guetteur.c"
#include "hifi.c"
#include "hybrid.c"
#include "input.c"
#include "jumelle.c"
#include "load.c"
#include "luciole.c"
#include "menu.c"
#include "meredenis.c"
#include "mite.c"
#include "moskito.c"
#include "moteur.c"
#include "neige.c"
#include "map.c"
#include "ngawe.c"
#include "objinit.c"
#include "objupdate.c"
#include "pmama.c"
#include "poing.c"
#include "poisson.c"
#include "worldmap.c"
#include "rand.c"
#include "ray.c"
#include "sound.c"
#include "save.c"
#include "saxo.c"
#include "screen.c"
#include "skops.c"
#include "special.c"
#include "stoneman.c"
#include "trumpet.c"
#include "ufo.c"
